"""add in_bank column

Revision ID: 066e6b08f65a
Revises: 
Create Date: 2025-03-27 21:53:05.856068

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '066e6b08f65a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crew',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=32), nullable=False),
    sa.Column('max_carry', sa.Integer(), nullable=False),
    sa.Column('current_carry', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.Column('is_pirate', sa.Boolean(), nullable=False),
    sa.Column('in_bank', sa.Integer(), nullable=True),
    sa.Column('debt', sa.Integer(), nullable=True),
    sa.Column('rice_count', sa.Integer(), nullable=True),
    sa.Column('tea_count', sa.Integer(), nullable=True),
    sa.Column('wine_count', sa.Integer(), nullable=True),
    sa.Column('spice_count', sa.Integer(), nullable=True),
    sa.Column('gold_count', sa.Integer(), nullable=True),
    sa.Column('diamonds_count', sa.Integer(), nullable=True),
    sa.Column('canon_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('game_timer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('port',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('pirate', sa.Boolean(), nullable=False),
    sa.Column('rice_price', sa.Integer(), nullable=False),
    sa.Column('tea_price', sa.Integer(), nullable=False),
    sa.Column('wine_price', sa.Integer(), nullable=False),
    sa.Column('spice_price', sa.Integer(), nullable=False),
    sa.Column('gold_price', sa.Integer(), nullable=False),
    sa.Column('diamonds_price', sa.Integer(), nullable=False),
    sa.Column('canon_price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('port')
    op.drop_table('game_timer')
    op.drop_table('crew')
    # ### end Alembic commands ###
