"""crew model items

Revision ID: 2e1c644ee5ae
Revises: 922ddbe97cee
Create Date: 2024-12-28 21:17:47.104680

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '2e1c644ee5ae'
down_revision = '922ddbe97cee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crew', schema=None) as batch_op:
        batch_op.alter_column('rice_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('tea_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('wine_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('spice_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('gold_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('diamonds_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('slaves_count',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crew', schema=None) as batch_op:
        batch_op.alter_column('slaves_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('diamonds_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('gold_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('spice_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('wine_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('tea_count',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('rice_count',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
