"""crew model item support 2

Revision ID: 32d11d72295b
Revises: e590d904ef64
Create Date: 2024-12-28 20:29:37.060173

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "32d11d72295b"
down_revision = "e590d904ef64"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crew", schema=None) as batch_op:
        batch_op.alter_column("max_carry", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("balance", existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crew", schema=None) as batch_op:
        batch_op.alter_column("balance", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("max_carry", existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###
