"""crew model items

Revision ID: 922ddbe97cee
Revises: b64c2ad028e8
Create Date: 2024-12-28 21:16:27.706852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922ddbe97cee'
down_revision = 'b64c2ad028e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crew', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rice_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('tea_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('wine_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('spice_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('gold_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('diamonds_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('slaves_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crew', schema=None) as batch_op:
        batch_op.drop_column('slaves_count')
        batch_op.drop_column('diamonds_count')
        batch_op.drop_column('gold_count')
        batch_op.drop_column('spice_count')
        batch_op.drop_column('wine_count')
        batch_op.drop_column('tea_count')
        batch_op.drop_column('rice_count')

    # ### end Alembic commands ###
