"""remove is_pirate default value

Revision ID: 949ca2fcc8f9
Revises: 
Create Date: 2025-03-02 20:59:15.994144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '949ca2fcc8f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crew',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=32), nullable=False),
    sa.Column('max_carry', sa.Integer(), nullable=False),
    sa.Column('current_carry', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.Column('is_pirate', sa.Boolean(), nullable=False),
    sa.Column('rice_count', sa.Integer(), nullable=True),
    sa.Column('tea_count', sa.Integer(), nullable=True),
    sa.Column('wine_count', sa.Integer(), nullable=True),
    sa.Column('spice_count', sa.Integer(), nullable=True),
    sa.Column('gold_count', sa.Integer(), nullable=True),
    sa.Column('diamonds_count', sa.Integer(), nullable=True),
    sa.Column('canon_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('port',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('pirate', sa.Boolean(), nullable=False),
    sa.Column('rice_price', sa.Integer(), nullable=False),
    sa.Column('tea_price', sa.Integer(), nullable=False),
    sa.Column('wine_price', sa.Integer(), nullable=False),
    sa.Column('spice_price', sa.Integer(), nullable=False),
    sa.Column('gold_price', sa.Integer(), nullable=False),
    sa.Column('diamonds_price', sa.Integer(), nullable=False),
    sa.Column('canon_price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('port')
    op.drop_table('crew')
    # ### end Alembic commands ###
