"""crew and ports

Revision ID: a75b2e3987e9
Revises: 17c835cff600
Create Date: 2024-12-27 19:07:37.334686

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a75b2e3987e9"
down_revision = "17c835cff600"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "port",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("pirate", sa.Boolean(), nullable=False),
        sa.Column("rice_price", sa.Integer(), nullable=False),
        sa.Column("tea_price", sa.Integer(), nullable=False),
        sa.Column("wine_price", sa.Integer(), nullable=False),
        sa.Column("spice_price", sa.Integer(), nullable=False),
        sa.Column("gold_price", sa.Integer(), nullable=False),
        sa.Column("diamonds_price", sa.Integer(), nullable=False),
        sa.Column("slaves_price", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.drop_table("user")
    op.drop_table("followers")
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_index("ix_post_timestamp")
        batch_op.drop_index("ix_post_user_id")

    op.drop_table("post")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "post",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("body", sa.VARCHAR(length=140), nullable=False),
        sa.Column("timestamp", sa.DATETIME(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.create_index("ix_post_user_id", ["user_id"], unique=False)
        batch_op.create_index("ix_post_timestamp", ["timestamp"], unique=False)

    op.create_table(
        "followers",
        sa.Column("follower_id", sa.INTEGER(), nullable=False),
        sa.Column("followed_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["followed_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["follower_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("follower_id", "followed_id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("username", sa.VARCHAR(length=64), nullable=False),
        sa.Column("email", sa.VARCHAR(length=120), nullable=False),
        sa.Column("password_hash", sa.VARCHAR(length=256), nullable=True),
        sa.Column("about_me", sa.VARCHAR(length=140), nullable=True),
        sa.Column("last_seen", sa.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("password_hash"),
        sa.UniqueConstraint("username"),
    )
    op.drop_table("port")
    # ### end Alembic commands ###
