"""crew model current cary upgrade

Revision ID: b64c2ad028e8
Revises: cd978ef2cbbd
Create Date: 2024-12-28 20:36:02.338351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b64c2ad028e8'
down_revision = 'cd978ef2cbbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crew', schema=None) as batch_op:
        batch_op.alter_column('current_carry',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crew', schema=None) as batch_op:
        batch_op.alter_column('current_carry',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
