"""crew model carry count

Revision ID: cd978ef2cbbd
Revises: 32d11d72295b
Create Date: 2024-12-28 20:32:04.158341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd978ef2cbbd'
down_revision = '32d11d72295b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crew', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_carry', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crew', schema=None) as batch_op:
        batch_op.drop_column('current_carry')

    # ### end Alembic commands ###
