"""add last_visited to crew

Revision ID: d8917f576e1e
Revises: 066e6b08f65a
Create Date: 2025-04-02 11:54:17.461319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8917f576e1e'
down_revision = '066e6b08f65a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crew', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_visited', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crew', schema=None) as batch_op:
        batch_op.drop_column('last_visited')

    # ### end Alembic commands ###
