"""crew model item support

Revision ID: e590d904ef64
Revises: bfefce774b9b
Create Date: 2024-12-28 20:27:56.657537

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e590d904ef64"
down_revision = "bfefce774b9b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crew", schema=None) as batch_op:
        batch_op.add_column(sa.Column("max_carry", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("balance", sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crew", schema=None) as batch_op:
        batch_op.drop_column("balance")
        batch_op.drop_column("max_carry")

    # ### end Alembic commands ###
